import type { Locale } from '@/lib/i18n';

/**
 * Economy copy is intentionally kept at the UI boundary.  Every supported
 * locale has a complete catalogue here so the economy surface never falls
 * back to Turkish or to an untranslated English string.
 *
 * Values are simulation copy only. A unit is one simulated ad worth $0.50 USD.
 */
export type EconomyUiKey =
  | 'economyTestLabel'
  | 'creditsBalance'
  | 'economyGateTitle'
  | 'economyGateBody'
  | 'economyGateProgress'
  | 'economyGateCancel'
  | 'economyGateContinue'
  | 'economyGateAdAction'
  | 'economyGateCreditApplied'
  | 'economyGateVipBypass'
  | 'economyGateNoRefund'
  | 'economySoloDaily'
  | 'economyTeamMatch'
  | 'economyRefill'
  | 'economyUnlock'
  | 'economyVision'
  | 'economyVip'
  | 'economyUsd'
  | 'economyAdValue'
  | 'economyMagazines'
  | 'economyInitialMagazines'
  | 'economyRefillReward'
  | 'economyExpiry'
  | 'economySimulationOnly';

type EconomyUiCopy = Record<EconomyUiKey, string>;

const COPY: Record<Locale, EconomyUiCopy> = {
  tr: {
    economyTestLabel: 'TEST / SİMÜLASYON',
    creditsBalance: 'Kredi bakiyesi',
    economyGateTitle: 'Operasyon erişimi',
    economyGateBody: 'Önce mevcut krediler kullanılır; kalan her birim için bir simüle reklamı ayrı ayrı tamamla.',
    economyGateProgress: 'İlerleme',
    economyGateCancel: 'İPTAL',
    economyGateContinue: 'DEVAM ET',
    economyGateAdAction: 'SİMÜLE REKLAMI TAMAMLA',
    economyGateCreditApplied: 'Kredi kullanıldı',
    economyGateVipBypass: 'VIP muafiyeti · reklam ve kredi yok',
    economyGateNoRefund: 'Tamamlanan reklam geri alınamaz. İptalde kullanılmayan kredi iade edilir.',
    economySoloDaily: 'Solo kamera erişimi yerel gün başına 3 birimdir.',
    economyTeamMatch: 'Her yeni takım maçı 3 birim gerektirir.',
    economyRefill: 'İkmal: 3 şarjör · 1 birim',
    economyUnlock: 'Açma: 1 birim · 24 saat',
    economyVision: 'Görüş modu: 1 birim · 24 saat',
    economyVip: 'VIP · $9.99 / takvim ayı',
    economyUsd: 'USD',
    economyAdValue: '1 simüle reklam = $0,50 USD',
    economyMagazines: 'şarjör',
    economyInitialMagazines: 'Toplam 3 ücretsiz şarjör: dolu + 2 yedek',
    economyRefillReward: 'Her ikmal 3 şarjör verir',
    economyExpiry: 'Bitiş',
    economySimulationOnly: 'TEST / SİMÜLASYON · gerçek ücret yok',
  },
  en: {
    economyTestLabel: 'TEST / SIMULATION',
    creditsBalance: 'Credit balance',
    economyGateTitle: 'Operation access',
    economyGateBody: 'Use available credits first, then complete one simulated ad for each remaining unit.',
    economyGateProgress: 'Progress',
    economyGateCancel: 'CANCEL',
    economyGateContinue: 'CONTINUE',
    economyGateAdAction: 'TAP TO COMPLETE SIMULATED AD',
    economyGateCreditApplied: 'Credit applied',
    economyGateVipBypass: 'VIP bypass · no ads or credits',
    economyGateNoRefund: 'Completed ads cannot be undone. Unused credit is returned when you cancel.',
    economySoloDaily: 'Solo camera access costs 3 units once per local day.',
    economyTeamMatch: 'Each new team match costs 3 units.',
    economyRefill: 'Refill: 3 magazines · 1 unit',
    economyUnlock: 'Unlock: 1 unit · 24 hours',
    economyVision: 'Vision mode: 1 unit · 24 hours',
    economyVip: 'VIP · $9.99 / calendar month',
    economyUsd: 'USD',
    economyAdValue: '1 simulated ad = $0.50 USD',
    economyMagazines: 'magazines',
    economyInitialMagazines: '3 free magazines total: loaded + 2 reserve',
    economyRefillReward: 'Each refill grants 3 magazines',
    economyExpiry: 'Expires',
    economySimulationOnly: 'TEST / SIMULATION · no real charge',
  },
  zh: {
    economyTestLabel: '测试 / 模拟',
    creditsBalance: '积分余额',
    economyGateTitle: '行动权限',
    economyGateBody: '先使用现有积分，然后为每个剩余单位分别完成一次模拟广告。',
    economyGateProgress: '进度',
    economyGateCancel: '取消',
    economyGateContinue: '继续',
    economyGateAdAction: '点击完成模拟广告',
    economyGateCreditApplied: '已使用积分',
    economyGateVipBypass: 'VIP 免除 · 无广告、无积分消耗',
    economyGateNoRefund: '已完成的广告无法撤回。取消时会退回未使用的积分。',
    economySoloDaily: '单人相机权限每天（本地日）需要 3 个单位。',
    economyTeamMatch: '每场新的团队比赛需要 3 个单位。',
    economyRefill: '补给：3 个弹匣 · 1 个单位',
    economyUnlock: '解锁：1 个单位 · 24 小时',
    economyVision: '视觉模式：1 个单位 · 24 小时',
    economyVip: 'VIP · $9.99 / 日历月',
    economyUsd: 'USD',
    economyAdValue: '1 次模拟广告 = $0.50 USD',
    economyMagazines: '弹匣',
    economyInitialMagazines: '共 3 个免费弹匣：已装填 + 2 个备用',
    economyRefillReward: '每次补给获得 3 个弹匣',
    economyExpiry: '到期',
    economySimulationOnly: '测试 / 模拟 · 不会真实扣款',
  },
  ja: {
    economyTestLabel: 'テスト / シミュレーション',
    creditsBalance: 'クレジット残高',
    economyGateTitle: '作戦アクセス',
    economyGateBody: 'まず利用可能なクレジットを使い、残りの各ユニットにつきシミュレーション広告を 1 回ずつ完了します。',
    economyGateProgress: '進行状況',
    economyGateCancel: 'キャンセル',
    economyGateContinue: '続ける',
    economyGateAdAction: 'タップしてシミュレーション広告を完了',
    economyGateCreditApplied: 'クレジットを使用',
    economyGateVipBypass: 'VIP 特典 · 広告・クレジット不要',
    economyGateNoRefund: '完了した広告は取り消せません。キャンセルすると未使用クレジットが戻ります。',
    economySoloDaily: 'ソロのカメラアクセスは現地日の 1 日 1 回、3 ユニットです。',
    economyTeamMatch: '新しいチーム戦 1 回につき 3 ユニットです。',
    economyRefill: '補給：マガジン 3 個 · 1 ユニット',
    economyUnlock: '解除：1 ユニット · 24 時間',
    economyVision: 'ビジョンモード：1 ユニット · 24 時間',
    economyVip: 'VIP · $9.99 / 暦月',
    economyUsd: 'USD',
    economyAdValue: 'シミュレーション広告 1 回 = $0.50 USD',
    economyMagazines: 'マガジン',
    economyInitialMagazines: '無料マガジン合計 3 個：装填済み + 予備 2 個',
    economyRefillReward: '補給 1 回でマガジン 3 個を付与',
    economyExpiry: '期限',
    economySimulationOnly: 'テスト / シミュレーション · 実際の請求なし',
  },
  ar: {
    economyTestLabel: 'اختبار / محاكاة',
    creditsBalance: 'رصيد الأرصدة',
    economyGateTitle: 'الوصول إلى المهمة',
    economyGateBody: 'استخدم الأرصدة المتاحة أولاً، ثم أكمل إعلاناً محاكياً لكل وحدة متبقية.',
    economyGateProgress: 'التقدم',
    economyGateCancel: 'إلغاء',
    economyGateContinue: 'متابعة',
    economyGateAdAction: 'اضغط لإكمال الإعلان المحاكى',
    economyGateCreditApplied: 'تم استخدام الرصيد',
    economyGateVipBypass: 'تجاوز VIP · بلا إعلانات أو أرصدة',
    economyGateNoRefund: 'لا يمكن التراجع عن الإعلانات المكتملة. يُعاد الرصيد غير المستخدم عند الإلغاء.',
    economySoloDaily: 'الوصول الفردي إلى الكاميرا يكلف 3 وحدات مرة كل يوم محلي.',
    economyTeamMatch: 'كل مباراة فريق جديدة تكلف 3 وحدات.',
    economyRefill: 'إعادة التزويد: 3 مخازن · وحدة واحدة',
    economyUnlock: 'فتح: وحدة واحدة · 24 ساعة',
    economyVision: 'وضع الرؤية: وحدة واحدة · 24 ساعة',
    economyVip: 'VIP · $9.99 / شهر تقويمي',
    economyUsd: 'USD',
    economyAdValue: 'إعلان محاكى واحد = $0.50 USD',
    economyMagazines: 'مخازن',
    economyInitialMagazines: '3 مخازن مجانية إجمالاً: مركب + 2 احتياطي',
    economyRefillReward: 'كل إعادة تزويد تمنح 3 مخازن',
    economyExpiry: 'ينتهي',
    economySimulationOnly: 'اختبار / محاكاة · بلا رسوم حقيقية',
  },
  de: {
    economyTestLabel: 'TEST / SIMULATION',
    creditsBalance: 'Guthaben',
    economyGateTitle: 'Zugriff auf den Einsatz',
    economyGateBody: 'Nutze zuerst vorhandenes Guthaben und schließe dann für jede verbleibende Einheit eine simulierte Werbung ab.',
    economyGateProgress: 'Fortschritt',
    economyGateCancel: 'ABBRECHEN',
    economyGateContinue: 'WEITER',
    economyGateAdAction: 'ANTIPPEN, UM SIMULIERTE WERBUNG ABZUSCHLIESSEN',
    economyGateCreditApplied: 'Guthaben verwendet',
    economyGateVipBypass: 'VIP-Umgehung · keine Werbung oder Guthabenkosten',
    economyGateNoRefund: 'Abgeschlossene Werbung kann nicht rückgängig gemacht werden. Nicht verwendetes Guthaben wird beim Abbrechen zurückgegeben.',
    economySoloDaily: 'Der Solo-Kamerazugriff kostet einmal pro lokalem Tag 3 Einheiten.',
    economyTeamMatch: 'Jedes neue Teamspiel kostet 3 Einheiten.',
    economyRefill: 'Nachfüllen: 3 Magazine · 1 Einheit',
    economyUnlock: 'Freischalten: 1 Einheit · 24 Stunden',
    economyVision: 'Sichtmodus: 1 Einheit · 24 Stunden',
    economyVip: 'VIP · $9.99 / Kalendermonat',
    economyUsd: 'USD',
    economyAdValue: '1 simulierte Werbung = $0,50 USD',
    economyMagazines: 'Magazine',
    economyInitialMagazines: 'Insgesamt 3 kostenlose Magazine: geladen + 2 Reserve',
    economyRefillReward: 'Jedes Nachfüllen gibt 3 Magazine',
    economyExpiry: 'Läuft ab',
    economySimulationOnly: 'TEST / SIMULATION · keine echte Abbuchung',
  },
  fr: {
    economyTestLabel: 'TEST / SIMULATION',
    creditsBalance: 'Solde de crédits',
    economyGateTitle: 'Accès à l’opération',
    economyGateBody: 'Utilisez d’abord les crédits disponibles, puis terminez une publicité simulée pour chaque unité restante.',
    economyGateProgress: 'Progression',
    economyGateCancel: 'ANNULER',
    economyGateContinue: 'CONTINUER',
    economyGateAdAction: 'TOUCHEZ POUR TERMINER LA PUBLICITÉ SIMULÉE',
    economyGateCreditApplied: 'Crédit utilisé',
    economyGateVipBypass: 'Avantage VIP · sans publicité ni crédit',
    economyGateNoRefund: 'Les publicités terminées sont irréversibles. Le crédit inutilisé est rendu en cas d’annulation.',
    economySoloDaily: 'L’accès caméra solo coûte 3 unités une fois par jour local.',
    economyTeamMatch: 'Chaque nouveau match en équipe coûte 3 unités.',
    economyRefill: 'Recharge : 3 chargeurs · 1 unité',
    economyUnlock: 'Déblocage : 1 unité · 24 heures',
    economyVision: 'Mode vision : 1 unité · 24 heures',
    economyVip: 'VIP · $9.99 / mois civil',
    economyUsd: 'USD',
    economyAdValue: '1 publicité simulée = $0,50 USD',
    economyMagazines: 'chargeurs',
    economyInitialMagazines: '3 chargeurs gratuits au total : chargé + 2 de réserve',
    economyRefillReward: 'Chaque recharge donne 3 chargeurs',
    economyExpiry: 'Expire',
    economySimulationOnly: 'TEST / SIMULATION · aucun débit réel',
  },
  es: {
    economyTestLabel: 'PRUEBA / SIMULACIÓN',
    creditsBalance: 'Saldo de créditos',
    economyGateTitle: 'Acceso a la operación',
    economyGateBody: 'Usa primero los créditos disponibles y completa un anuncio simulado por cada unidad restante.',
    economyGateProgress: 'Progreso',
    economyGateCancel: 'CANCELAR',
    economyGateContinue: 'CONTINUAR',
    economyGateAdAction: 'TOCA PARA COMPLETAR EL ANUNCIO SIMULADO',
    economyGateCreditApplied: 'Crédito aplicado',
    economyGateVipBypass: 'Ventaja VIP · sin anuncios ni créditos',
    economyGateNoRefund: 'Los anuncios completados no se pueden deshacer. El crédito no usado se devuelve al cancelar.',
    economySoloDaily: 'El acceso de cámara en solitario cuesta 3 unidades una vez por día local.',
    economyTeamMatch: 'Cada nuevo combate por equipos cuesta 3 unidades.',
    economyRefill: 'Recarga: 3 cargadores · 1 unidad',
    economyUnlock: 'Desbloqueo: 1 unidad · 24 horas',
    economyVision: 'Modo de visión: 1 unidad · 24 horas',
    economyVip: 'VIP · $9.99 / mes natural',
    economyUsd: 'USD',
    economyAdValue: '1 anuncio simulado = $0,50 USD',
    economyMagazines: 'cargadores',
    economyInitialMagazines: '3 cargadores gratis en total: cargado + 2 de reserva',
    economyRefillReward: 'Cada recarga concede 3 cargadores',
    economyExpiry: 'Caduca',
    economySimulationOnly: 'PRUEBA / SIMULACIÓN · sin cobro real',
  },
  it: {
    economyTestLabel: 'TEST / SIMULAZIONE',
    creditsBalance: 'Saldo crediti',
    economyGateTitle: 'Accesso all’operazione',
    economyGateBody: 'Usa prima i crediti disponibili, poi completa una pubblicità simulata per ogni unità rimanente.',
    economyGateProgress: 'Avanzamento',
    economyGateCancel: 'ANNULLA',
    economyGateContinue: 'CONTINUA',
    economyGateAdAction: 'TOCCA PER COMPLETARE LA PUBBLICITÀ SIMULATA',
    economyGateCreditApplied: 'Credito usato',
    economyGateVipBypass: 'Vantaggio VIP · niente pubblicità o crediti',
    economyGateNoRefund: 'Le pubblicità completate non possono essere annullate. Il credito inutilizzato viene restituito annullando.',
    economySoloDaily: 'L’accesso alla fotocamera in solitaria costa 3 unità una volta al giorno locale.',
    economyTeamMatch: 'Ogni nuova partita a squadre costa 3 unità.',
    economyRefill: 'Rifornimento: 3 caricatori · 1 unità',
    economyUnlock: 'Sblocco: 1 unità · 24 ore',
    economyVision: 'Modalità visione: 1 unità · 24 ore',
    economyVip: 'VIP · $9.99 / mese solare',
    economyUsd: 'USD',
    economyAdValue: '1 pubblicità simulata = $0,50 USD',
    economyMagazines: 'caricatori',
    economyInitialMagazines: '3 caricatori gratuiti in totale: caricato + 2 di riserva',
    economyRefillReward: 'Ogni rifornimento concede 3 caricatori',
    economyExpiry: 'Scade',
    economySimulationOnly: 'TEST / SIMULAZIONE · nessun addebito reale',
  },
  pt: {
    economyTestLabel: 'TESTE / SIMULAÇÃO',
    creditsBalance: 'Saldo de créditos',
    economyGateTitle: 'Acesso à operação',
    economyGateBody: 'Use primeiro os créditos disponíveis e conclua um anúncio simulado para cada unidade restante.',
    economyGateProgress: 'Progresso',
    economyGateCancel: 'CANCELAR',
    economyGateContinue: 'CONTINUAR',
    economyGateAdAction: 'TOQUE PARA CONCLUIR O ANÚNCIO SIMULADO',
    economyGateCreditApplied: 'Crédito usado',
    economyGateVipBypass: 'Benefício VIP · sem anúncios ou créditos',
    economyGateNoRefund: 'Anúncios concluídos não podem ser desfeitos. O crédito não usado volta ao cancelar.',
    economySoloDaily: 'O acesso solo à câmera custa 3 unidades uma vez por dia local.',
    economyTeamMatch: 'Cada nova partida em equipe custa 3 unidades.',
    economyRefill: 'Recarga: 3 carregadores · 1 unidade',
    economyUnlock: 'Desbloqueio: 1 unidade · 24 horas',
    economyVision: 'Modo de visão: 1 unidade · 24 horas',
    economyVip: 'VIP · $9.99 / mês civil',
    economyUsd: 'USD',
    economyAdValue: '1 anúncio simulado = $0,50 USD',
    economyMagazines: 'carregadores',
    economyInitialMagazines: '3 carregadores grátis no total: carregado + 2 reservas',
    economyRefillReward: 'Cada recarga concede 3 carregadores',
    economyExpiry: 'Expira',
    economySimulationOnly: 'TESTE / SIMULAÇÃO · sem cobrança real',
  },
  ru: {
    economyTestLabel: 'ТЕСТ / СИМУЛЯЦИЯ',
    creditsBalance: 'Баланс кредитов',
    economyGateTitle: 'Доступ к операции',
    economyGateBody: 'Сначала используются доступные кредиты, затем для каждой оставшейся единицы нужно завершить отдельную симуляцию рекламы.',
    economyGateProgress: 'Прогресс',
    economyGateCancel: 'ОТМЕНА',
    economyGateContinue: 'ПРОДОЛЖИТЬ',
    economyGateAdAction: 'НАЖМИТЕ, ЧТОБЫ ЗАВЕРШИТЬ СИМУЛЯЦИЮ РЕКЛАМЫ',
    economyGateCreditApplied: 'Кредит использован',
    economyGateVipBypass: 'Преимущество VIP · без рекламы и кредитов',
    economyGateNoRefund: 'Завершённую рекламу нельзя отменить. Неиспользованный кредит возвращается при отмене.',
    economySoloDaily: 'Доступ к камере в одиночной игре стоит 3 единицы раз в местный день.',
    economyTeamMatch: 'Каждый новый командный матч стоит 3 единицы.',
    economyRefill: 'Пополнение: 3 магазина · 1 единица',
    economyUnlock: 'Разблокировка: 1 единица · 24 часа',
    economyVision: 'Режим обзора: 1 единица · 24 часа',
    economyVip: 'VIP · $9.99 / календарный месяц',
    economyUsd: 'USD',
    economyAdValue: '1 симулированная реклама = $0,50 USD',
    economyMagazines: 'магазины',
    economyInitialMagazines: 'Всего 3 бесплатных магазина: заряженный + 2 запасных',
    economyRefillReward: 'Каждое пополнение даёт 3 магазина',
    economyExpiry: 'Истекает',
    economySimulationOnly: 'ТЕСТ / СИМУЛЯЦИЯ · реального списания нет',
  },
  uk: {
    economyTestLabel: 'ТЕСТ / СИМУЛЯЦІЯ',
    creditsBalance: 'Баланс кредитів',
    economyGateTitle: 'Доступ до операції',
    economyGateBody: 'Спочатку використовуються доступні кредити, а потім для кожної залишкової одиниці потрібно завершити окрему симуляцію реклами.',
    economyGateProgress: 'Прогрес',
    economyGateCancel: 'СКАСУВАТИ',
    economyGateContinue: 'ПРОДОВЖИТИ',
    economyGateAdAction: 'НАТИСНІТЬ, ЩОБ ЗАВЕРШИТИ СИМУЛЯЦІЮ РЕКЛАМИ',
    economyGateCreditApplied: 'Кредит використано',
    economyGateVipBypass: 'Перевага VIP · без реклами та кредитів',
    economyGateNoRefund: 'Завершену рекламу не можна скасувати. Невикористаний кредит повертається після скасування.',
    economySoloDaily: 'Доступ до камери в соло коштує 3 одиниці раз на місцеву добу.',
    economyTeamMatch: 'Кожен новий командний матч коштує 3 одиниці.',
    economyRefill: 'Поповнення: 3 магазини · 1 одиниця',
    economyUnlock: 'Розблокування: 1 одиниця · 24 години',
    economyVision: 'Режим огляду: 1 одиниця · 24 години',
    economyVip: 'VIP · $9.99 / календарний місяць',
    economyUsd: 'USD',
    economyAdValue: '1 симульована реклама = $0,50 USD',
    economyMagazines: 'магазини',
    economyInitialMagazines: 'Усього 3 безкоштовні магазини: заряджений + 2 запасні',
    economyRefillReward: 'Кожне поповнення дає 3 магазини',
    economyExpiry: 'Завершується',
    economySimulationOnly: 'ТЕСТ / СИМУЛЯЦІЯ · реального списання немає',
  },
  hi: {
    economyTestLabel: 'टेस्ट / सिमुलेशन',
    creditsBalance: 'क्रेडिट शेष',
    economyGateTitle: 'ऑपरेशन एक्सेस',
    economyGateBody: 'पहले उपलब्ध क्रेडिट इस्तेमाल करें, फिर हर बचे हुए यूनिट के लिए एक सिम्युलेटेड विज्ञापन पूरा करें।',
    economyGateProgress: 'प्रगति',
    economyGateCancel: 'रद्द करें',
    economyGateContinue: 'जारी रखें',
    economyGateAdAction: 'सिम्युलेटेड विज्ञापन पूरा करने के लिए टैप करें',
    economyGateCreditApplied: 'क्रेडिट इस्तेमाल हुआ',
    economyGateVipBypass: 'VIP लाभ · विज्ञापन या क्रेडिट नहीं',
    economyGateNoRefund: 'पूरे किए गए विज्ञापन वापस नहीं लिए जा सकते। रद्द करने पर अप्रयुक्त क्रेडिट लौटता है।',
    economySoloDaily: 'सोलो कैमरा एक्सेस की कीमत स्थानीय दिन में एक बार 3 यूनिट है।',
    economyTeamMatch: 'हर नए टीम मैच की कीमत 3 यूनिट है।',
    economyRefill: 'रीफिल: 3 मैगज़ीन · 1 यूनिट',
    economyUnlock: 'अनलॉक: 1 यूनिट · 24 घंटे',
    economyVision: 'विज़न मोड: 1 यूनिट · 24 घंटे',
    economyVip: 'VIP · $9.99 / कैलेंडर माह',
    economyUsd: 'USD',
    economyAdValue: '1 सिम्युलेटेड विज्ञापन = $0.50 USD',
    economyMagazines: 'मैगज़ीन',
    economyInitialMagazines: 'कुल 3 मुफ़्त मैगज़ीन: लोडेड + 2 रिज़र्व',
    economyRefillReward: 'हर रीफिल 3 मैगज़ीन देता है',
    economyExpiry: 'समाप्ति',
    economySimulationOnly: 'टेस्ट / सिमुलेशन · कोई वास्तविक शुल्क नहीं',
  },
  ur: {
    economyTestLabel: 'ٹیسٹ / سمولیشن',
    creditsBalance: 'کریڈٹ بیلنس',
    economyGateTitle: 'آپریشن تک رسائی',
    economyGateBody: 'پہلے دستیاب کریڈٹ استعمال کریں، پھر ہر باقی یونٹ کے لیے ایک سمولیٹڈ اشتہار مکمل کریں۔',
    economyGateProgress: 'پیش رفت',
    economyGateCancel: 'منسوخ',
    economyGateContinue: 'جاری رکھیں',
    economyGateAdAction: 'سمولیٹڈ اشتہار مکمل کرنے کے لیے ٹیپ کریں',
    economyGateCreditApplied: 'کریڈٹ استعمال ہوا',
    economyGateVipBypass: 'VIP سہولت · اشتہار یا کریڈٹ نہیں',
    economyGateNoRefund: 'مکمل کیے گئے اشتہارات واپس نہیں ہو سکتے۔ منسوخ کرنے پر غیر استعمال شدہ کریڈٹ واپس ملتا ہے۔',
    economySoloDaily: 'سولو کیمرا رسائی مقامی دن میں ایک بار 3 یونٹس کی ہے۔',
    economyTeamMatch: 'ہر نئے ٹیم میچ کے لیے 3 یونٹس ہیں۔',
    economyRefill: 'ری فل: 3 میگزین · 1 یونٹ',
    economyUnlock: 'ان لاک: 1 یونٹ · 24 گھنٹے',
    economyVision: 'وژن موڈ: 1 یونٹ · 24 گھنٹے',
    economyVip: 'VIP · $9.99 / کیلنڈر ماہ',
    economyUsd: 'USD',
    economyAdValue: '1 سمولیٹڈ اشتہار = $0.50 USD',
    economyMagazines: 'میگزین',
    economyInitialMagazines: 'کل 3 مفت میگزین: لوڈ شدہ + 2 اضافی',
    economyRefillReward: 'ہر ری فل 3 میگزین دیتا ہے',
    economyExpiry: 'میعاد',
    economySimulationOnly: 'ٹیسٹ / سمولیشن · کوئی حقیقی چارج نہیں',
  },
  bn: {
    economyTestLabel: 'টেস্ট / সিমুলেশন',
    creditsBalance: 'ক্রেডিট ব্যালান্স',
    economyGateTitle: 'অপারেশন অ্যাক্সেস',
    economyGateBody: 'আগে উপলব্ধ ক্রেডিট ব্যবহার করুন, তারপর বাকি প্রতিটি ইউনিটের জন্য একটি করে সিমুলেটেড বিজ্ঞাপন সম্পূর্ণ করুন।',
    economyGateProgress: 'অগ্রগতি',
    economyGateCancel: 'বাতিল',
    economyGateContinue: 'চালিয়ে যান',
    economyGateAdAction: 'সিমুলেটেড বিজ্ঞাপন শেষ করতে ট্যাপ করুন',
    economyGateCreditApplied: 'ক্রেডিট ব্যবহার হয়েছে',
    economyGateVipBypass: 'VIP সুবিধা · বিজ্ঞাপন বা ক্রেডিট নেই',
    economyGateNoRefund: 'সম্পূর্ণ বিজ্ঞাপন ফেরানো যায় না। বাতিল করলে অব্যবহৃত ক্রেডিট ফেরত আসে।',
    economySoloDaily: 'সোলো ক্যামেরা অ্যাক্সেস স্থানীয় দিনে একবার ৩ ইউনিট।',
    economyTeamMatch: 'প্রতিটি নতুন টিম ম্যাচে ৩ ইউনিট লাগে।',
    economyRefill: 'রিফিল: ৩টি ম্যাগাজিন · ১ ইউনিট',
    economyUnlock: 'আনলক: ১ ইউনিট · ২৪ ঘণ্টা',
    economyVision: 'ভিশন মোড: ১ ইউনিট · ২৪ ঘণ্টা',
    economyVip: 'VIP · $9.99 / ক্যালেন্ডার মাস',
    economyUsd: 'USD',
    economyAdValue: '১টি সিমুলেটেড বিজ্ঞাপন = $0.50 USD',
    economyMagazines: 'ম্যাগাজিন',
    economyInitialMagazines: 'মোট ৩টি বিনামূল্যের ম্যাগাজিন: লোড করা + ২টি রিজার্ভ',
    economyRefillReward: 'প্রতি রিফিলে ৩টি ম্যাগাজিন মেলে',
    economyExpiry: 'মেয়াদ শেষ',
    economySimulationOnly: 'টেস্ট / সিমুলেশন · কোনো আসল চার্জ নেই',
  },
  pa: {
    economyTestLabel: 'ਟੈਸਟ / ਸਿਮੂਲੇਸ਼ਨ',
    creditsBalance: 'ਕ੍ਰੈਡਿਟ ਬਕਾਇਆ',
    economyGateTitle: 'ਓਪਰੇਸ਼ਨ ਪਹੁੰਚ',
    economyGateBody: 'ਪਹਿਲਾਂ ਉਪਲਬਧ ਕ੍ਰੈਡਿਟ ਵਰਤੋ, ਫਿਰ ਹਰ ਬਾਕੀ ਯੂਨਿਟ ਲਈ ਇੱਕ ਸਿਮੂਲੇਟ ਕੀਤਾ ਵਿਗਿਆਪਨ ਪੂਰਾ ਕਰੋ।',
    economyGateProgress: 'ਤਰੱਕੀ',
    economyGateCancel: 'ਰੱਦ ਕਰੋ',
    economyGateContinue: 'ਜਾਰੀ ਰੱਖੋ',
    economyGateAdAction: 'ਸਿਮੂਲੇਟ ਕੀਤਾ ਵਿਗਿਆਪਨ ਪੂਰਾ ਕਰਨ ਲਈ ਟੈਪ ਕਰੋ',
    economyGateCreditApplied: 'ਕ੍ਰੈਡਿਟ ਵਰਤਿਆ ਗਿਆ',
    economyGateVipBypass: 'VIP ਲਾਭ · ਵਿਗਿਆਪਨ ਜਾਂ ਕ੍ਰੈਡਿਟ ਨਹੀਂ',
    economyGateNoRefund: 'ਪੂਰੇ ਕੀਤੇ ਵਿਗਿਆਪਨ ਵਾਪਸ ਨਹੀਂ ਕੀਤੇ ਜਾ ਸਕਦੇ। ਰੱਦ ਕਰਨ ਤੇ ਨਾ ਵਰਤਿਆ ਕ੍ਰੈਡਿਟ ਵਾਪਸ ਮਿਲਦਾ ਹੈ।',
    economySoloDaily: 'ਸੋਲੋ ਕੈਮਰਾ ਪਹੁੰਚ ਸਥਾਨਕ ਦਿਨ ਵਿੱਚ ਇੱਕ ਵਾਰ 3 ਯੂਨਿਟ ਹੈ।',
    economyTeamMatch: 'ਹਰ ਨਵੇਂ ਟੀਮ ਮੈਚ ਲਈ 3 ਯੂਨਿਟ ਹਨ।',
    economyRefill: 'ਰੀਫਿਲ: 3 ਮੈਗਜ਼ੀਨ · 1 ਯੂਨਿਟ',
    economyUnlock: 'ਅਨਲੌਕ: 1 ਯੂਨਿਟ · 24 ਘੰਟੇ',
    economyVision: 'ਵਿਜ਼ਨ ਮੋਡ: 1 ਯੂਨਿਟ · 24 ਘੰਟੇ',
    economyVip: 'VIP · $9.99 / ਕੈਲੰਡਰ ਮਹੀਨਾ',
    economyUsd: 'USD',
    economyAdValue: '1 ਸਿਮੂਲੇਟ ਕੀਤਾ ਵਿਗਿਆਪਨ = $0.50 USD',
    economyMagazines: 'ਮੈਗਜ਼ੀਨ',
    economyInitialMagazines: 'ਕੁੱਲ 3 ਮੁਫ਼ਤ ਮੈਗਜ਼ੀਨ: ਲੋਡ ਕੀਤਾ + 2 ਰਿਜ਼ਰਵ',
    economyRefillReward: 'ਹਰ ਰੀਫਿਲ 3 ਮੈਗਜ਼ੀਨ ਦਿੰਦਾ ਹੈ',
    economyExpiry: 'ਮਿਆਦ',
    economySimulationOnly: 'ਟੈਸਟ / ਸਿਮੂਲੇਸ਼ਨ · ਕੋਈ ਅਸਲ ਚਾਰਜ ਨਹੀਂ',
  },
  id: {
    economyTestLabel: 'UJI / SIMULASI',
    creditsBalance: 'Saldo kredit',
    economyGateTitle: 'Akses operasi',
    economyGateBody: 'Gunakan kredit yang tersedia terlebih dahulu, lalu selesaikan satu iklan simulasi untuk setiap unit yang tersisa.',
    economyGateProgress: 'Kemajuan',
    economyGateCancel: 'BATAL',
    economyGateContinue: 'LANJUTKAN',
    economyGateAdAction: 'KETUK UNTUK MENYELESAIKAN IKLAN SIMULASI',
    economyGateCreditApplied: 'Kredit digunakan',
    economyGateVipBypass: 'Manfaat VIP · tanpa iklan atau kredit',
    economyGateNoRefund: 'Iklan yang selesai tidak dapat dibatalkan. Kredit yang tidak digunakan dikembalikan saat kamu membatalkan.',
    economySoloDaily: 'Akses kamera solo membutuhkan 3 unit sekali setiap hari lokal.',
    economyTeamMatch: 'Setiap pertandingan tim baru membutuhkan 3 unit.',
    economyRefill: 'Isi ulang: 3 magasin · 1 unit',
    economyUnlock: 'Buka: 1 unit · 24 jam',
    economyVision: 'Mode visi: 1 unit · 24 jam',
    economyVip: 'VIP · $9.99 / bulan kalender',
    economyUsd: 'USD',
    economyAdValue: '1 iklan simulasi = $0,50 USD',
    economyMagazines: 'magasin',
    economyInitialMagazines: 'Total 3 magasin gratis: terpasang + 2 cadangan',
    economyRefillReward: 'Setiap isi ulang memberi 3 magasin',
    economyExpiry: 'Berakhir',
    economySimulationOnly: 'UJI / SIMULASI · tanpa biaya nyata',
  },
  ko: {
    economyTestLabel: '테스트 / 시뮬레이션',
    creditsBalance: '크레딧 잔액',
    economyGateTitle: '작전 이용',
    economyGateBody: '먼저 사용 가능한 크레딧을 쓰고, 남은 각 유닛마다 시뮬레이션 광고를 하나씩 완료하세요.',
    economyGateProgress: '진행',
    economyGateCancel: '취소',
    economyGateContinue: '계속',
    economyGateAdAction: '탭하여 시뮬레이션 광고 완료',
    economyGateCreditApplied: '크레딧 사용됨',
    economyGateVipBypass: 'VIP 혜택 · 광고 및 크레딧 없음',
    economyGateNoRefund: '완료한 광고는 되돌릴 수 없습니다. 취소하면 사용하지 않은 크레딧이 반환됩니다.',
    economySoloDaily: '솔로 카메라 이용은 현지 날짜마다 한 번, 3유닛입니다.',
    economyTeamMatch: '새 팀 매치마다 3유닛이 필요합니다.',
    economyRefill: '보급: 탄창 3개 · 1유닛',
    economyUnlock: '잠금 해제: 1유닛 · 24시간',
    economyVision: '시야 모드: 1유닛 · 24시간',
    economyVip: 'VIP · $9.99 / 달력 기준 한 달',
    economyUsd: 'USD',
    economyAdValue: '시뮬레이션 광고 1회 = $0.50 USD',
    economyMagazines: '탄창',
    economyInitialMagazines: '무료 탄창 총 3개: 장착 1개 + 예비 2개',
    economyRefillReward: '보급할 때마다 탄창 3개 지급',
    economyExpiry: '만료',
    economySimulationOnly: '테스트 / 시뮬레이션 · 실제 청구 없음',
  },
  vi: {
    economyTestLabel: 'KIỂM TRA / MÔ PHỎNG',
    creditsBalance: 'Số dư tín dụng',
    economyGateTitle: 'Quyền truy cập nhiệm vụ',
    economyGateBody: 'Dùng tín dụng hiện có trước, sau đó hoàn thành một quảng cáo mô phỏng cho mỗi đơn vị còn lại.',
    economyGateProgress: 'Tiến độ',
    economyGateCancel: 'HỦY',
    economyGateContinue: 'TIẾP TỤC',
    economyGateAdAction: 'CHẠM ĐỂ HOÀN TẤT QUẢNG CÁO MÔ PHỎNG',
    economyGateCreditApplied: 'Đã dùng tín dụng',
    economyGateVipBypass: 'Đặc quyền VIP · không quảng cáo hoặc tín dụng',
    economyGateNoRefund: 'Không thể hoàn tác quảng cáo đã hoàn tất. Tín dụng chưa dùng sẽ được trả khi hủy.',
    economySoloDaily: 'Quyền camera solo tốn 3 đơn vị một lần mỗi ngày địa phương.',
    economyTeamMatch: 'Mỗi trận đấu đội mới tốn 3 đơn vị.',
    economyRefill: 'Nạp lại: 3 băng đạn · 1 đơn vị',
    economyUnlock: 'Mở khóa: 1 đơn vị · 24 giờ',
    economyVision: 'Chế độ nhìn: 1 đơn vị · 24 giờ',
    economyVip: 'VIP · $9.99 / tháng theo lịch',
    economyUsd: 'USD',
    economyAdValue: '1 quảng cáo mô phỏng = $0,50 USD',
    economyMagazines: 'băng đạn',
    economyInitialMagazines: 'Tổng 3 băng đạn miễn phí: đã nạp + 2 dự phòng',
    economyRefillReward: 'Mỗi lần nạp lại nhận 3 băng đạn',
    economyExpiry: 'Hết hạn',
    economySimulationOnly: 'KIỂM TRA / MÔ PHỎNG · không tính phí thật',
  },
  th: {
    economyTestLabel: 'ทดสอบ / จำลอง',
    creditsBalance: 'ยอดเครดิต',
    economyGateTitle: 'สิทธิ์เข้าปฏิบัติการ',
    economyGateBody: 'ใช้เครดิตที่มีอยู่ก่อน แล้วทำโฆษณาจำลองให้ครบหนึ่งครั้งต่อหนึ่งหน่วยที่เหลือ',
    economyGateProgress: 'ความคืบหน้า',
    economyGateCancel: 'ยกเลิก',
    economyGateContinue: 'ดำเนินการต่อ',
    economyGateAdAction: 'แตะเพื่อทำโฆษณาจำลองให้เสร็จ',
    economyGateCreditApplied: 'ใช้เครดิตแล้ว',
    economyGateVipBypass: 'สิทธิ์ VIP · ไม่ใช้โฆษณาหรือเครดิต',
    economyGateNoRefund: 'โฆษณาที่ทำเสร็จแล้วเรียกคืนไม่ได้ เครดิตที่ยังไม่ใช้จะคืนเมื่อยกเลิก',
    economySoloDaily: 'การเข้ากล้องโซโลใช้ 3 หน่วยวันละครั้งตามวันท้องถิ่น',
    economyTeamMatch: 'การแข่งขันทีมใหม่แต่ละครั้งใช้ 3 หน่วย',
    economyRefill: 'เติมกระสุน: 3 แมกกาซีน · 1 หน่วย',
    economyUnlock: 'ปลดล็อก: 1 หน่วย · 24 ชั่วโมง',
    economyVision: 'โหมดการมองเห็น: 1 หน่วย · 24 ชั่วโมง',
    economyVip: 'VIP · $9.99 / เดือนปฏิทิน',
    economyUsd: 'USD',
    economyAdValue: 'โฆษณาจำลอง 1 ครั้ง = $0.50 USD',
    economyMagazines: 'แมกกาซีน',
    economyInitialMagazines: 'แมกกาซีนฟรีทั้งหมด 3 ชิ้น: ใส่อยู่ + สำรอง 2 ชิ้น',
    economyRefillReward: 'การเติมแต่ละครั้งให้แมกกาซีน 3 ชิ้น',
    economyExpiry: 'หมดอายุ',
    economySimulationOnly: 'ทดสอบ / จำลอง · ไม่มีการเรียกเก็บเงินจริง',
  },
  nl: {
    economyTestLabel: 'TEST / SIMULATIE',
    creditsBalance: 'Creditsaldo',
    economyGateTitle: 'Toegang tot de operatie',
    economyGateBody: 'Gebruik eerst beschikbare credits en voltooi daarna één gesimuleerde advertentie per resterende eenheid.',
    economyGateProgress: 'Voortgang',
    economyGateCancel: 'ANNULEREN',
    economyGateContinue: 'DOORGAAN',
    economyGateAdAction: 'TIK OM DE GESIMULEERDE ADVERTENTIE TE VOLTOOIEN',
    economyGateCreditApplied: 'Credit gebruikt',
    economyGateVipBypass: 'VIP-voordeel · geen advertenties of credits',
    economyGateNoRefund: 'Voltooide advertenties kunnen niet worden teruggedraaid. Ongebruikte credits worden bij annuleren teruggegeven.',
    economySoloDaily: 'Solo-cameratoegang kost eenmaal per lokale dag 3 eenheden.',
    economyTeamMatch: 'Elke nieuwe teamwedstrijd kost 3 eenheden.',
    economyRefill: 'Bijvullen: 3 magazijnen · 1 eenheid',
    economyUnlock: 'Ontgrendelen: 1 eenheid · 24 uur',
    economyVision: 'Zichtmodus: 1 eenheid · 24 uur',
    economyVip: 'VIP · $9.99 / kalendermaand',
    economyUsd: 'USD',
    economyAdValue: '1 gesimuleerde advertentie = $0,50 USD',
    economyMagazines: 'magazijnen',
    economyInitialMagazines: 'In totaal 3 gratis magazijnen: geladen + 2 reserve',
    economyRefillReward: 'Elke bijvulling geeft 3 magazijnen',
    economyExpiry: 'Verloopt',
    economySimulationOnly: 'TEST / SIMULATIE · geen echte afschrijving',
  },
  pl: {
    economyTestLabel: 'TEST / SYMULACJA',
    creditsBalance: 'Saldo kredytów',
    economyGateTitle: 'Dostęp do operacji',
    economyGateBody: 'Najpierw użyj dostępnych kredytów, a potem ukończ jedną symulowaną reklamę za każdą pozostałą jednostkę.',
    economyGateProgress: 'Postęp',
    economyGateCancel: 'ANULUJ',
    economyGateContinue: 'KONTYNUUJ',
    economyGateAdAction: 'DOTKNIJ, ABY UKOŃCZYĆ SYMULOWANĄ REKLAMĘ',
    economyGateCreditApplied: 'Użyto kredytu',
    economyGateVipBypass: 'Korzyść VIP · bez reklam i kredytów',
    economyGateNoRefund: 'Ukończonych reklam nie można cofnąć. Niewykorzystany kredyt wraca po anulowaniu.',
    economySoloDaily: 'Dostęp do kamery solo kosztuje 3 jednostki raz na lokalny dzień.',
    economyTeamMatch: 'Każdy nowy mecz drużynowy kosztuje 3 jednostki.',
    economyRefill: 'Uzupełnienie: 3 magazynki · 1 jednostka',
    economyUnlock: 'Odblokowanie: 1 jednostka · 24 godziny',
    economyVision: 'Tryb widzenia: 1 jednostka · 24 godziny',
    economyVip: 'VIP · $9.99 / miesiąc kalendarzowy',
    economyUsd: 'USD',
    economyAdValue: '1 symulowana reklama = $0,50 USD',
    economyMagazines: 'magazynki',
    economyInitialMagazines: 'Łącznie 3 darmowe magazynki: załadowany + 2 zapasowe',
    economyRefillReward: 'Każde uzupełnienie daje 3 magazynki',
    economyExpiry: 'Wygasa',
    economySimulationOnly: 'TEST / SYMULACJA · bez prawdziwej opłaty',
  },
  sv: {
    economyTestLabel: 'TEST / SIMULERING',
    creditsBalance: 'Kreditsaldo',
    economyGateTitle: 'Åtkomst till operationen',
    economyGateBody: 'Använd tillgängliga krediter först och slutför sedan en simulerad annons för varje återstående enhet.',
    economyGateProgress: 'Förlopp',
    economyGateCancel: 'AVBRYT',
    economyGateContinue: 'FORTSÄTT',
    economyGateAdAction: 'TRYCK FÖR ATT SLUTFÖRA SIMULERAD ANNONS',
    economyGateCreditApplied: 'Kredit använd',
    economyGateVipBypass: 'VIP-förmån · inga annonser eller krediter',
    economyGateNoRefund: 'Slutförda annonser kan inte ångras. Oanvänd kredit återbetalas när du avbryter.',
    economySoloDaily: 'Soloåtkomst till kameran kostar 3 enheter en gång per lokal dag.',
    economyTeamMatch: 'Varje ny lagmatch kostar 3 enheter.',
    economyRefill: 'Påfyllning: 3 magasin · 1 enhet',
    economyUnlock: 'Lås upp: 1 enhet · 24 timmar',
    economyVision: 'Siktläge: 1 enhet · 24 timmar',
    economyVip: 'VIP · $9.99 / kalendermånad',
    economyUsd: 'USD',
    economyAdValue: '1 simulerad annons = $0,50 USD',
    economyMagazines: 'magasin',
    economyInitialMagazines: 'Totalt 3 kostnadsfria magasin: laddat + 2 i reserv',
    economyRefillReward: 'Varje påfyllning ger 3 magasin',
    economyExpiry: 'Går ut',
    economySimulationOnly: 'TEST / SIMULERING · ingen riktig debitering',
  },
  fa: {
    economyTestLabel: 'آزمایش / شبیه‌سازی',
    creditsBalance: 'موجودی اعتبار',
    economyGateTitle: 'دسترسی به عملیات',
    economyGateBody: 'ابتدا از اعتبار موجود استفاده کنید، سپس برای هر واحد باقی‌مانده یک تبلیغ شبیه‌سازی‌شده را کامل کنید.',
    economyGateProgress: 'پیشرفت',
    economyGateCancel: 'لغو',
    economyGateContinue: 'ادامه',
    economyGateAdAction: 'برای تکمیل تبلیغ شبیه‌سازی‌شده لمس کنید',
    economyGateCreditApplied: 'اعتبار استفاده شد',
    economyGateVipBypass: 'مزیت VIP · بدون تبلیغ یا اعتبار',
    economyGateNoRefund: 'تبلیغ‌های کامل‌شده قابل برگشت نیستند. با لغو، اعتبار استفاده‌نشده برگردانده می‌شود.',
    economySoloDaily: 'دسترسی دوربین تک‌نفره روزی یک‌بار (روز محلی) ۳ واحد است.',
    economyTeamMatch: 'هر مسابقه تیمی جدید ۳ واحد هزینه دارد.',
    economyRefill: 'پرکردن: ۳ خشاب · ۱ واحد',
    economyUnlock: 'بازکردن: ۱ واحد · ۲۴ ساعت',
    economyVision: 'حالت دید: ۱ واحد · ۲۴ ساعت',
    economyVip: 'VIP · $9.99 / ماه تقویمی',
    economyUsd: 'USD',
    economyAdValue: '۱ تبلیغ شبیه‌سازی‌شده = $0.50 USD',
    economyMagazines: 'خشاب',
    economyInitialMagazines: 'در مجموع ۳ خشاب رایگان: خشاب‌گذاری‌شده + ۲ یدک',
    economyRefillReward: 'هر پرکردن ۳ خشاب می‌دهد',
    economyExpiry: 'پایان',
    economySimulationOnly: 'آزمایش / شبیه‌سازی · بدون هزینه واقعی',
  },
};

export function economyText(locale: Locale, key: EconomyUiKey): string {
  return COPY[locale][key];
}

export const REWARDED_AD_VALUE_CENTS = 50;
export const GATE_UNITS = 3;
export const REFILL_UNITS = 1;
export const REFILL_MAGAZINES = 3;
export const UNLOCK_DURATION_HOURS = 24;
export const VIP_PRICE_USD_CENTS = 999;

/**
 * Number formatting follows the selected locale while the simulated currency
 * remains fixed to USD.
 */
const INTL_LOCALE: Record<Locale, string> = {
  tr: 'tr-TR',
  en: 'en-US',
  zh: 'zh-CN',
  ja: 'ja-JP',
  ar: 'ar',
  de: 'de-DE',
  fr: 'fr-FR',
  es: 'es-ES',
  it: 'it-IT',
  pt: 'pt-BR',
  ru: 'ru-RU',
  uk: 'uk-UA',
  hi: 'hi-IN',
  ur: 'ur-PK',
  bn: 'bn-BD',
  pa: 'pa-IN',
  id: 'id-ID',
  ko: 'ko-KR',
  vi: 'vi-VN',
  th: 'th-TH',
  nl: 'nl-NL',
  pl: 'pl-PL',
  sv: 'sv-SE',
  fa: 'fa-IR',
};

export function formatUsdFromCents(cents: number, locale: Locale = 'tr'): string {
  const value = Math.max(0, Math.floor(cents)) / 100;
  return new Intl.NumberFormat(INTL_LOCALE[locale], {
    style: 'currency',
    currency: 'USD',
    currencyDisplay: 'symbol',
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(value);
}

export function localDayKey(now = new Date()): string {
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, '0');
  const day = String(now.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}