import type { ImageSourcePropType } from 'react-native';
import type { WeaponId } from './weapons';

export const WEAPON_IMAGES: Record<WeaponId, ImageSourcePropType> = {
  'glock-17': require('../assets/images/weapons/glock-17.png'),
  'desert-eagle': require('../assets/images/weapons/desert-eagle.png'),
  mp5: require('../assets/images/weapons/mp5.png'),
  p90: require('../assets/images/weapons/p90.png'),
  m4a1: require('../assets/images/weapons/m4a1.png'),
  'ak-47': require('../assets/images/weapons/ak-47.png'),
  hk416: require('../assets/images/weapons/hk416.png'),
  g3: require('../assets/images/weapons/g3.png'),
  m16a4: require('../assets/images/weapons/m16a4.png'),
  akm: require('../assets/images/weapons/akm.png'),
  'scar-l': require('../assets/images/weapons/scar-l.png'),
  g36c: require('../assets/images/weapons/g36c.png'),
  famas: require('../assets/images/weapons/famas.png'),
  'aug-a3': require('../assets/images/weapons/aug-a3.png'),
  uzi: require('../assets/images/weapons/uzi.png'),
  'remington-870': require('../assets/images/weapons/remington-870.png'),
  'benelli-m4': require('../assets/images/weapons/benelli-m4.png'),
  awp: require('../assets/images/weapons/awp.png'),
  'barrett-m82': require('../assets/images/weapons/barrett-m82.png'),
  'dragunov-svd': require('../assets/images/weapons/dragunov-svd.png'),
  m249: require('../assets/images/weapons/m249.png'),
  mg42: require('../assets/images/weapons/mg42.png'),
  mg3: require('../assets/images/weapons/mg3.png'),
  pkm: require('../assets/images/weapons/pkm.png'),
  'minigun-m134': require('../assets/images/weapons/minigun-m134.png'),
  'frag-grenade': require('../assets/images/weapons/frag-grenade.png'),
  flashbang: require('../assets/images/weapons/flashbang-clean.png'),
  'smoke-grenade': require('../assets/images/weapons/smoke-grenade.png'),
  bazooka: require('../assets/images/weapons/bazooka.png'),
  'rpg-7': require('../assets/images/weapons/rpg-7.png'),
  at4: require('../assets/images/weapons/at4.png'),
  'laser-rifle': require('../assets/images/weapons/laser-rifle.png'),
  'electric-arc': require('../assets/images/weapons/electric-arc.png'),
  slingshot: require('../assets/images/weapons/slingshot.png'),
  knife: require('../assets/images/weapons/knife.png'),
};

export const WEAPON_FPS_IMAGES: Partial<Record<WeaponId, ImageSourcePropType>> = {
  'glock-17': require('../assets/images/weapons-fps/glock-17.png'),
  'desert-eagle': require('../assets/images/weapons-fps/desert-eagle.png'),
  mp5: require('../assets/images/weapons-fps/mp5.png'),
  p90: require('../assets/images/weapons-fps/p90.png'),
  m4a1: require('../assets/images/weapons-fps/m4a1.png'),
  'ak-47': require('../assets/images/weapons-fps/ak-47.png'),
  hk416: require('../assets/images/weapons-fps/hk416.png'),
  g3: require('../assets/images/weapons-fps/g3.png'),
  m16a4: require('../assets/images/weapons-fps/m16a4.png'),
  akm: require('../assets/images/weapons-fps/akm.png'),
  'scar-l': require('../assets/images/weapons-fps/scar-l.png'),
  g36c: require('../assets/images/weapons-fps/g36c.png'),
  famas: require('../assets/images/weapons-fps/famas.png'),
  'aug-a3': require('../assets/images/weapons-fps/aug-a3.png'),
  uzi: require('../assets/images/weapons-fps/uzi.png'),
  'remington-870': require('../assets/images/weapons-fps/remington-870.png'),
  'benelli-m4': require('../assets/images/weapons-fps/benelli-m4.png'),
  awp: require('../assets/images/weapons-fps/awp.png'),
  'barrett-m82': require('../assets/images/weapons-fps/barrett-m82.png'),
  'dragunov-svd': require('../assets/images/weapons-fps/dragunov-svd.png'),
  m249: require('../assets/images/weapons-fps/m249.png'),
  mg42: require('../assets/images/weapons-fps/mg42.png'),
  mg3: require('../assets/images/weapons-fps/mg3.png'),
  pkm: require('../assets/images/weapons-fps/pkm.png'),
  'minigun-m134': require('../assets/images/weapons-fps/minigun-m134.png'),
  bazooka: require('../assets/images/weapons-fps/bazooka.png'),
  'rpg-7': require('../assets/images/weapons-fps/rpg-7.png'),
  at4: require('../assets/images/weapons-fps/at4.png'),
  'laser-rifle': require('../assets/images/weapons-fps/laser-rifle.png'),
  'electric-arc': require('../assets/images/weapons-fps/electric-arc.png'),
  slingshot: require('../assets/images/weapons-fps/slingshot.png'),
  knife: require('../assets/images/weapons-fps/knife.png'),
};

export const WEAPON_SOUNDS: Record<WeaponId, number> = {
  'glock-17': require('../assets/audio/weapons/glock-17-boosted.mp3'),
  'desert-eagle': require('../assets/audio/weapons/desert-eagle.mp3'),
  mp5: require('../assets/audio/weapons/mp5-boosted.mp3'),
  p90: require('../assets/audio/weapons/p90-boosted.mp3'),
  m4a1: require('../assets/audio/weapons/m4a1.mp3'),
  'ak-47': require('../assets/audio/weapons/ak-47-boosted.mp3'),
  hk416: require('../assets/audio/weapons/hk416.mp3'),
  g3: require('../assets/audio/weapons/g3.mp3'),
  m16a4: require('../assets/audio/weapons/m16a4.mp3'),
  akm: require('../assets/audio/weapons/akm.mp3'),
  'scar-l': require('../assets/audio/weapons/scar-l-boosted.mp3'),
  g36c: require('../assets/audio/weapons/g36c.mp3'),
  famas: require('../assets/audio/weapons/famas-boosted.mp3'),
  'aug-a3': require('../assets/audio/weapons/aug-a3.mp3'),
  uzi: require('../assets/audio/weapons/uzi.mp3'),
  'remington-870': require('../assets/audio/weapons/remington-870.mp3'),
  'benelli-m4': require('../assets/audio/weapons/benelli-m4.mp3'),
  awp: require('../assets/audio/weapons/awp.mp3'),
  'barrett-m82': require('../assets/audio/weapons/barrett-m82-boosted.mp3'),
  'dragunov-svd': require('../assets/audio/weapons/dragunov-svd.mp3'),
  m249: require('../assets/audio/weapons/m249.mp3'),
  mg42: require('../assets/audio/weapons/mg42.mp3'),
  mg3: require('../assets/audio/weapons/mg3.mp3'),
  pkm: require('../assets/audio/weapons/pkm.mp3'),
  'minigun-m134': require('../assets/audio/weapons/minigun-m134.mp3'),
  'frag-grenade': require('../assets/audio/weapons/frag-grenade.mp3'),
  flashbang: require('../assets/audio/weapons/flashbang-boosted.mp3'),
  'smoke-grenade': require('../assets/audio/weapons/smoke-grenade.mp3'),
  bazooka: require('../assets/audio/weapons/bazooka.mp3'),
  'rpg-7': require('../assets/audio/weapons/rpg-7.mp3'),
  at4: require('../assets/audio/weapons/at4.mp3'),
  'laser-rifle': require('../assets/audio/weapons/laser-rifle.mp3'),
  'electric-arc': require('../assets/audio/weapons/electric-arc.mp3'),
  slingshot: require('../assets/audio/weapons/slingshot.mp3'),
  knife: require('../assets/audio/weapons/knife.mp3'),
};